### ISSUE TITLE
Exit gracefully if the Base OS is unknown

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#121]
See #117 for more info.

```
2018-11-07 12:31:41,261 - DEBUG - tern - Starting...
2018-11-07 12:31:41,268 - DEBUG - container - Running command: docker ps
2018-11-07 12:31:41,344 - DEBUG - report - Setting up...
2018-11-07 12:31:45,410 - DEBUG - container - Running command: docker images docker.io/hello-world:latest
2018-11-07 12:31:45,478 - DEBUG - container - Running command: docker save docker.io/hello-world:latest
[sudo] password for nisha: 
2018-11-07 12:31:51,953 - DEBUG - rootfs - Running command: sudo mount -o bind temp/f22789aafb439644ab76948424a0c1b64f328cecde82c95edad3813aaadbe077/contents temp/mergedir
2018-11-07 12:31:52,019 - WARNING - command_lib - No listing for key . Consider adding this listing to command_lib/base.yml.

2018-11-07 12:31:52,020 - WARNING - report - No shell listing in command library. Using default shell
Traceback (most recent call last):
  File "./tern", line 91, in <module>
    main(args)
  File "./tern", line 47, in main
    report.execute_docker_image(args)
  File "/home/nisha/tern3.7/tern/report/report.py", line 393, in execute_docker_image
    analyze_docker_image(full_image)
  File "/home/nisha/tern3.7/tern/report/report.py", line 176, in analyze_docker_image
    binary, default_shell=constants.shell)
KeyError: 'binary'
```
Docker's `hello-world` container image contains only one file which can be executed in a shell. It doesn't exist as a binary in `command_lib/base.yml` so it is a good image to test this bug against.

**Comment by nishakm** [comment]
Error occurs because of a formatting syntax error. Nevertheless, there are some changes to reporting.
