### ISSUE TITLE
KeyError: openjdk:8

### ISSUE THREAD

**Issue by sbtaylor15** [vmware/tern#18]
I am getting this error.   Where should I look to get more info on whats happening?

Thanks, Steve

```
2018-03-13 15:47:37,642 - ternlog - DEBUG - Starting...
2018-03-13 15:47:37,642 - ternlog - DEBUG - Creating Report...
2018-03-13 15:47:37,642 - ternlog - DEBUG - Creating a detailed report on components in Docker image...
2018-03-13 15:47:37,644 - ternlog - DEBUG - Running command: sudo docker images openjdk:8
2018-03-13 15:47:37,920 - ternlog - DEBUG - Running command: sudo docker save openjdk:8
2018-03-13 15:48:36,594 - ternlog - DEBUG - Nothing in cache for layer a64142d97d. Invoking from command library
2018-03-13 15:48:36,594 - ternlog - DEBUG - Running command: sudo docker ps -a --filter name=tern-container
2018-03-13 15:48:36,740 - ternlog - DEBUG - Running command: sudo docker run -td --name tern-container openjdk:8
2018-03-13 15:48:39,968 - ternlog - WARNING - No listing of openjdk:8 in the command library. To add one, make an
entry in command_lib/base.yml
2018-03-13 15:48:39,969 - ternlog - DEBUG - Running command: sudo docker ps -a --filter name=tern-container
2018-03-13 15:48:40,172 - ternlog - DEBUG - Running command: sudo docker stop tern-container
2018-03-13 15:48:41,428 - ternlog - DEBUG - Running command: sudo docker rm tern-container
2018-03-13 15:48:44,839 - ternlog - DEBUG - Running command: sudo docker images openjdk:8
2018-03-13 15:48:45,232 - ternlog - DEBUG - Running command: sudo docker rmi -f openjdk:8
2018-03-13 15:48:45,570 - ternlog - DEBUG - Running command: sudo docker images tern-image:1520977657
2018-03-13 15:48:45,951 - ternlog - DEBUG - Running command: sudo docker build -t tern-image:1520977657 -f Dockerfile .
Traceback (most recent call last):
  File "./tern", line 87, in <module>
    main(args, logger)
  File "./tern", line 34, in main
    report.execute(args)
  File "/root/ternenv/tern/report.py", line 280, in execute
    shell = common.get_image_shell(base_image_msg[0])
  File "/root/ternenv/tern/common.py", line 92, in get_image_shell
    'base'][base_image_tag[0]]['tags'][base_image_tag[1]]['shell']
KeyError: 'openjdk'
```

Here is the Dockerfile

```
FROM openjdk:8
EXPOSE 8080
ENV DBHome /opt/deployhub
ENV DBUserName  postgres
ENV DBPassword  postgres
ENV DBConnectionString jdbc:postgresql://dh-db.gotdns.com:5432/postgres
ENV DBDriverName org.postgresql.Driver

RUN mkdir /opt/deployhub
RUN mkdir /opt/deployhub/engine
RUN apt-get update
RUN apt-get -y install net-tools
ADD webapp-runner.jar /opt/deployhub
ADD dh-ms-general.war /opt/deployhub
CMD java -jar /opt/deployhub/webapp-runner.jar --path /dmadminweb /opt/deployhub/dh-ms-general.war 2>&1
```

**Comment by sbtaylor15** [comment]
Figured it out.   The ```
WARNING - No listing of openjdk:8 in the command library. To add one, make an
entry in command_lib/base.yml
``` should really be an error since adding the following to command_lib/base.yml fixed the error.

```
# openjdk -------------------------------------------------------------------------------------------------------------------------------
openjdk:
  latest: '8'
  tags:
    '8':
        shell: '/bin/bash'
        # either enter the package names as a list or a snippet to invoke either within or outside the container
        names:
          invoke:
            1:
              # Currently two types of environments are supported - host or container
              container:
                - "dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'"
          delimiter: "\n"
        # the length of this list should be the same as the names or else there will be a mismatch
        versions:
          invoke:
            1:
              container:
                - "pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`"
                - "for p in $pkgs; do dpkg -l $p | awk 'NR>5 {print $3}'; done"
          delimiter: "\n"
        licenses:
          invoke:
            1:
              container:
                - "pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`"
                - "for p in $pkgs; do cat /usr/share/doc/$p/copyright; echo EOF; done"
          delimiter: 'EOF'
        src_urls: {}
```
