### ISSUE TITLE
python string object has no Attribute 'format_map' when running through a Docker entrypoint

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#23]
Dockerfile:

FROM docker:18.02.0-ce

WORKDIR /root/

RUN apk add --no-cache git python3 sudo bash py-pip

RUN python3 -m venv ternenv
WORKDIR /root/ternenv
RUN git clone https://github.com/vmware/tern.git
RUN /bin/bash -c "source bin/activate"
WORKDIR /root/ternenv/tern
RUN pip install -r requirements.txt
ENTRYPOINT ["./tern", "report", "-d"]
CMD ["samples/photon_git/Dockerfile"]

docker commands:
docker build -t dtern .
docker run -v /var/run/docker.sock:/var/run/docker.sock dtern

Traceback:
2018-03-22 12:12:47,614 - ternlog - DEBUG - Running command: sudo docker run -td --name tern-container vmware/photon:1.0
Traceback (most recent call last):
  File "./tern", line 87, in <module>
    main(args, logger)
  File "./tern", line 34, in main
    report.execute(args)
  File "/root/ternenv/tern/report.py", line 271, in execute
    logger)
  File "/root/ternenv/tern/report.py", line 127, in print_image_base
    package_list = common.get_packages_from_base(base_image_msg[0])
  File "/root/ternenv/tern/common.py", line 161, in get_packages_from_base
    names = cmds.get_pkg_attr_list(info['shell'], info['names'])
  File "/root/ternenv/tern/utils/commands.py", line 382, in get_pkg_attr_list
    package=package_name, override=override)
  File "/root/ternenv/tern/utils/commands.py", line 347, in invoke_in_container
    FormatAwk(package=package)) + ' && '
AttributeError: 'str' object has no attribute 'format_map'

This originates from the file:
https://github.com/vmware/tern/blob/master/utils/commands.py  line 346 and 347
full_cmd = full_cmd + snippet_list[index].format_map(FormatAwk(package=package)) + ' && '

The Docker container is running python 3.6.3 so format_map should be supported.

Strangely, this works fine for a docker container without ENTRYPOINT and running with the -it option.

**Comment by nishakm** [comment]
RUN /bin/bash -c "source bin/activate" does not work while building a container.
The side effect is that python2 is used not python3 as tern has a #!/usr/bin/env python. format_map is not supported in python2.

However, running it using python3 errors out: 
File "/root/tern/utils/commands.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by nishakm** [comment]
Some workaround is needed in order to make the Dockerfile to work:
RUN pip3 install -r /root/tern/requirements.txt <-- use pip3 to get python3 modules
WORKDIR /root/tern/
RUN sed -i '1d' tern <-- remove the shebang from the executable
ENTRYPOINT ["python3", "tern", "report", "-d"] <-- run using python3
CMD ["samples/photon_git/Dockerfile"]

The executable's shebang needs to point to python3 not python

**Comment by nishakm** [comment]
https://github.com/vmware/tern/commit/ddc9a6455a06f124b875eb4e3b4ad7987589f846
changes the shebang to python3
