### ISSUE TITLE
Wrap python2.7 error message with user-friendly error message

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#362]
**Describe the Feature**
If you run Tern in an environment that defaults to Python2.7 you get the following output:

```
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/tern/__main__.py", line 128, in main
    do_main(args)
  File "/usr/local/lib/python2.7/site-packages/tern/__main__.py", line 73, in do_main
    report.execute_docker_image(args)
  File "/usr/local/lib/python2.7/site-packages/tern/report/report.py", line 438, in execute_docker_image
    full_image = load_full_image(args.docker_image)
  File "/usr/local/lib/python2.7/site-packages/tern/report/report.py", line 140, in load_full_image
    test_image = DockerImage(image_tag_string)
  File "/usr/local/lib/python2.7/site-packages/tern/classes/docker_image.py", line 30, in __init__
    super().__init__(image_id)
TypeError: super() takes at least 1 argument (0 given)
```

I propose wrapping the raw output with a more user-friendly error message. Something to the effect of "Error running Tern. Please check that python3 is configured as default."

**Use Cases**
This would be helpful to new users who do think they have python3 installed on their system but do not have it configured as default.

**Implementation Changes**
The error is being hit in `tern/classes/docker_image.py.` Might consider using the `traceback library: https://docs.python.org/3/library/traceback.html`

**Comment by AyahRamahi** [comment]
I am a beginner, but I would like to work on this issue, can I?

**Comment by rnjudge** [comment]
@AyahRamahi Go for it! We always love help. Let us know if you have any questions.
