### ISSUE TITLE
Update documentation regarding to scancode

### ISSUE THREAD

**Issue by Siggitrain** [vmware/tern#532]
**Description**
Please update / fix the documentation of the installation process for scancode.

**Implementation**
There are two possible ways:
- Way 1: Use pip package (preferred)
  Step 1: Update README.md: 'pip install tern scancode' should be 'pip install tern scancode-toolkit'
  Step 2: Update scancode executor and remove './' from the scancode commands

- Way 2: Execute inside bin
  Step 1: Update README.md: 'pip install tern scancode' should be 'pip install tern scancode-toolkit'
  Step 2: Update README.md: Execute tern inside the bin directory of the venv, so that ./scancode can be found

**References**
https://github.com/vmware/tern/blob/master/tern/extensions/scancode/executor.py

**Original error**
`2020-02-10 14:59:44,099 - DEBUG - rootfs - Running command: ./scancode -lpcu --quiet --json - /home/siggitrain/.tern/temp/484556bdfad5ceed68ecb52cee08d4dd331f8890f808e54b1a810fc6c7ef0f7a/contents
Traceback (most recent call last):
  File "/home/siggitrain/docker_analysis/ternenv/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 170, in main
    do_main(args)
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 93, in do_main
    run.execute_docker_image(args)
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/analyze/docker/run.py", line 88, in execute_docker_image
    analyze(full_image, args)
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/analyze/docker/run.py", line 65, in analyze
    run_extension(image_obj, args.extend)
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/analyze/passthrough.py", line 84, in run_extension
    return mgr.driver.execute(image_obj)
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/extensions/scancode/executor.py", line 39, in execute
    if not passthrough.run_on_image(image_obj, command):
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/analyze/passthrough.py", line 68, in run_on_image
    if not execute_external_command(layer, full_cmd):
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/analyze/passthrough.py", line 41, in execute_external_command
    result, error = rootfs.shell_command(command)
  File "/home/siggitrain/docker_analysis/ternenv/lib/python3.6/site-packages/tern/utils/rootfs.py", line 93, in shell_command
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './scancode': './scancode'`

**Comment by nishakm** [comment]
@Siggitrain Thanks for filing the issue. We've recently fixed this and it will be available in our next pip release.
