### ISSUE TITLE
Unable to scan OpenSUSE Tumbleweed image

### ISSUE THREAD

**Issue by oc37ejuc** [vmware/tern#538]
**Describe the bug**
Tern fails trying to scan OpenSUSE Tumbleweed image.

**To Reproduce**
1. execute `tern -l report  -f spdxtagvalue -i 1d71b22e34c0`

**Error in terminal**
```
2020-02-16 17:00:00,058 - ERROR - rootfs - b'mount: /home/oc37ejuc/.tern/temp/mergedir/proc: mount point does not exist.\n'
Traceback (most recent call last):
  File "/home/oc37ejuc/ternenv/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 170, in main
    do_main(args)
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 93, in do_main
    run.execute_docker_image(args)
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/analyze/docker/run.py", line 88, in execute_docker_image
    analyze(full_image, args)
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/analyze/docker/run.py", line 67, in analyze
    analyze_docker_image(image_obj, args.redo, is_dockerfile)
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/analyze/docker/analyze.py", line 37, in analyze_docker_image
    shell = analyze_first_layer(image_obj, master_list, redo)
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/analyze/docker/analyze.py", line 98, in analyze_first_layer
    rootfs.prep_rootfs(target)
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/utils/rootfs.py", line 177, in prep_rootfs
    root_command(mount_proc, os.path.join(rootfs_path, 'proc'))
  File "/home/oc37ejuc/ternenv/lib/python3.6/site-packages/tern/utils/rootfs.py", line 79, in root_command
    1, cmd=full_cmd, output=error)
subprocess.CalledProcessError: Command '['sudo', 'mount', '-t', 'proc', '/proc', '/home/oc37ejuc/.tern/temp/mergedir/proc']' returned non-zero exit status 1.
```

**Expected behavior**
Tern should not fail.

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
Tern version 1.0.1
- Operating System (Linux Distro and version or Mac or Windows)
Ubuntu 18.04 
- Vagrant file
n.A.
- Container OS
n.A.
- Python version (3.6 or higher)
3.6.9
- Cloud environment (AWS, Azure, GCP)
n.A.

**Please attach files if they exist**
- [tern.log](https://github.com/vmware/tern/files/4210384/tern.log)

**Comment by nishakm** [comment]
@oc37ejuc is this image available for us to take a look at?

**Comment by oc37ejuc** [comment]
@nishakm It is, yes. The Image is (or was when I filed the bug) the current build that you can get from Dockerhub. I kept the Image Id in the bug report for reproducibility :)

**Comment by nishakm** [comment]
Thanks! This is the first OBS image we've come across and it doesn't have a `/dev`, `/sys`, or `/proc` mountpoint
```
~/.tern/temp/f46cf2321c63860dccc7776e16cb4ea8613549b9faa6887485c8feba04457d45/contents $ ls
bin  etc  home  lib  lib64  mnt  opt  root  run  sbin  selinux  srv  tmp  usr  var
```
...which is interesting because when spinning up the container you can see all the above mountpoints:

```
$ docker run -it opensuse/tumbleweed:latest
e4e90895e042:/ # ls
bin  dev  etc  home  lib  lib64  mnt  opt  proc  root  run  sbin  selinux  srv	sys  tmp  usr  var
```
It looks like we need to check if these mountpoints exist before attempting to mount them.

**Comment by nishakm** [comment]
To fix, modify:
```
def prep_rootfs(rootfs_dir):
    '''Mount required filesystems in the rootfs directory'''
    rootfs_path = os.path.abspath(rootfs_dir)
   # check here if os.path.join(rootfs_path, 'proc') actually exists
   # if it doesn't exist, make it
   # repeat for sys and dev mountpoints
    try:
        root_command(mount_proc, os.path.join(rootfs_path, 'proc'))
        root_command(mount_sys, os.path.join(rootfs_path, 'sys'))
        root_command(mount_dev, os.path.join(rootfs_path, 'dev'))
        root_command(host_dns, os.path.join(
            rootfs_path, constants.resolv_path[1:]))
    except subprocess.CalledProcessError as error:
        logger.error("%s", error.output)
        raise <-- stretch goal: raise subprocess.CalledProcessError with the error.output
```

**Comment by abhaykatheria** [comment]
@nishakm I would like to work on this issue
