### ISSUE TITLE
mount: /root/.tern/temp/mergedir: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error

### ISSUE THREAD

**Issue by tminussi** [vmware/tern#566]
**Describe the bug**
Once I was able to move forward with #556, I stumbled upon another problem which has been a little bit hard to debug.

I have been able to _dockerize_ `tern` and the reports run just fine for some images, like [debian](https://hub.docker.com/_/debian) and [ubuntu](https://hub.docker.com/_/ubuntu), but it fails when running the reports for [postgres](https://hub.docker.com/_/postgres) or [openjdk](https://hub.docker.com/_/openjdk). I am sure there are some other success/failure cases, but so far these are the only ones I have come across.

The specific error is `Command failed. mount: /root/.tern/temp/mergedir: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.`.

I have installed both `cifs-utils` and `nfs-utils` in my Docker image and the `/sbin/` directory contains all the mount files which apparently are necessary: `mount.cifs | mount.nfs | mount.nfs4 | mount.zfs`

**To Reproduce**
1. Create a Dockerfile with the following content:
```
FROM docker:dind

RUN apk --no-cache add \
      git \
      findutils \
      util-linux \
      tar \
      cifs-utils \
      nfs-utils \
      attr && \
    rm -rf /var/cache/apk/*

RUN apk add python3

RUN pip3 install --upgrade pip && pip3 install tern

CMD ["sh"]
```
2. Build its image by running `docker build -t yourimage .`
3. Run the recently built image in `--privileged` mode: `docker run --privileged -it --rm -v /var/run/docker.sock:/var/run/docker.sock yourimage sh`
4. Try to run a report for one of the offending images: `tern -l report -o output.txt -i postgres`
5. The error will be displayed

**Error in terminal**
```
2020-03-02 12:57:51,531 - DEBUG - rootfs - Running command: mount -t overlay overlay -o lowerdir=/root/.tern/temp/3e29b193cb0e97576e20170819724cf94c46c8d745136268e355db1342221572/contents,upperdir=/root/.tern/temp/94ed5c3b66967a82b8493c65480f35bba0842e8eff97a428b74152bcc2ed7d28/contents,workdir=/root/.tern/temp/workdir /root/.tern/temp/mergedir
2020-03-02 12:57:51,538 - ERROR - rootfs - Command failed. mount: /root/.tern/temp/mergedir: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.

Traceback (most recent call last):
  File "/usr/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/tern/__main__.py", line 170, in main
    do_main(args)
  File "/usr/lib/python3.8/site-packages/tern/__main__.py", line 93, in do_main
    run.execute_docker_image(args)
  File "/usr/lib/python3.8/site-packages/tern/analyze/docker/run.py", line 88, in execute_docker_image
    analyze(full_image, args)
  File "/usr/lib/python3.8/site-packages/tern/analyze/docker/run.py", line 67, in analyze
    analyze_docker_image(image_obj, args.redo, is_dockerfile)
  File "/usr/lib/python3.8/site-packages/tern/analyze/docker/analyze.py", line 39, in analyze_docker_image
    analyze_subsequent_layers(image_obj, shell, master_list, redo)
  File "/usr/lib/python3.8/site-packages/tern/analyze/docker/analyze.py", line 133, in analyze_subsequent_layers
    target = mount_overlay_fs(image_obj, curr_layer)
  File "/usr/lib/python3.8/site-packages/tern/analyze/docker/analyze.py", line 178, in mount_overlay_fs
    target = rootfs.mount_diff_layers(tar_layers)
  File "/usr/lib/python3.8/site-packages/tern/utils/rootfs.py", line 209, in mount_diff_layers
    root_command(union_mount, args, merge_dir_path)
  File "/usr/lib/python3.8/site-packages/tern/utils/rootfs.py", line 78, in root_command
    raise subprocess.CalledProcessError(  # nosec
subprocess.CalledProcessError: Command '['mount', '-t', 'overlay', 'overlay', '-o', 'lowerdir=/root/.tern/temp/3e29b193cb0e97576e20170819724cf94c46c8d745136268e355db1342221572/contents,upperdir=/root/.tern/temp/94ed5c3b66967a82b8493c65480f35bba0842e8eff97a428b74152bcc2ed7d28/contents,workdir=/root/.tern/temp/workdir', '/root/.tern/temp/mergedir']' returned non-zero exit status 1.
```

**Expected behavior**
Reports should be generated like they are for some other images, like [debian](https://hub.docker.com/_/debian) and [ubuntu](https://hub.docker.com/_/ubuntu)

**Environment you are running Tern on**
- Tern version 1.0.1
- python version = 3.8.2 (default, Feb 29 2020, 17:03:31)
- Alpine

**Please attach files if they exist**
- tern.log
- report.*

**Comment by rnjudge** [comment]
The error is due to the fact that you cannot overlay mount inside a docker container. The reason you don't see it for debian and ubuntu is because those images only have one layer so the error is not hit. We faced this issue earlier for tern's default container in https://github.com/vmware/tern/pull/500. You will want to use the bind mount command line option for running Tern in a docker container. The mount point needs to be somewhere outside the container.

```
  -b BIND_DIR, --bind-mount BIND_DIR
                        Absolute path to bind mount target. Needed when running from within a container.
```

If you notice, Tern's Dockefile uses this command line option where yours is missing a similar entrypoint:
```ENTRYPOINT ["tern", "-b", "/hostmount"]```

**Comment by tminussi** [comment]
Thanks, @rnjudge.
I had noticed that command indeed, but when I managed to run debian images without any issues, I was like: "well, that command is there for a reason, I just haven't figured out why just yet, so I will keep on going". 
Now, thanks to you, I know what that command is for.

I will close this issue.

Thanks!
