### ISSUE TITLE
`tern report` fails on OS X

### ISSUE THREAD

**Issue by ivanayov** [vmware/tern#73]
`./tern report -i <docker image>` fails on OS X with 
```
2018-08-08 16:31:40,419 - DEBUG - rootfs - Running command: sudo mount -o bind temp/b9eddca1757ae022ff3a77cf03ae6cbb221853f83efaef570a76414cd534e7ff/contents temp/mergedir
Traceback (most recent call last):
  File "./tern", line 94, in <module>
    main(args)
  File "./tern", line 53, in main
    report.execute_docker_image(args)
  File "/Users/iyovcheva/go/src/github.com/openfaas/certifier/ternenv/tern/report/report.py", line 321, in execute_docker_image
    analyze_docker_image(full_image)
  File "/Users/iyovcheva/go/src/github.com/openfaas/certifier/ternenv/tern/report/report.py", line 142, in analyze_docker_image
    target = rootfs.mount_base_layer(image_obj.layers[0].tar_file)
  File "/Users/iyovcheva/go/src/github.com/openfaas/certifier/ternenv/tern/utils/rootfs.py", line 108, in mount_base_layer
    root_command(mount, base_rootfs_path, target_dir_path)
  File "/Users/iyovcheva/go/src/github.com/openfaas/certifier/ternenv/tern/utils/rootfs.py", line 56, in root_command
    raise subprocess.CalledProcessError(1, cmd=full_cmd, output=error)
subprocess.CalledProcessError: Command '['sudo', 'mount', '-o', 'bind', 'temp/b9eddca1757ae022ff3a77cf03ae6cbb221853f83efaef570a76414cd534e7ff/contents', 'temp/mergedir']' returned non-zero exit status 1.
```

Steps to reproduce:
```
$ python3 -m venv ternenv
$ cd ternenv
$ git clone https://github.com/vmware/tern.git
$ source bin/activate
$ cd tern
$ git checkout -b release v0.1.0
$ pip install -r requirements.tx

$ ./tern report -i my-image:latest
```

**Comment by nishakm** [comment]
@jtcasper or @ivanayov can you paste here what storage driver your Docker engine uses? Also, if it's not too much trouble, can you try to switch your storage driver to overlay2?https://docs.docker.com/storage/storagedriver/select-storage-driver/

**Comment by nishakm** [comment]
Created #79 for the Vagrant file creation.
