### ISSUE TITLE
tern overlay mount fails for golang image

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#82]
```
./tern report -i ./tern -k report -i docker.io/golang
...
2018-09-10 17:16:35,797 - DEBUG - rootfs - Running command: sudo mount -t overlay overlay -o lowerdir=temp/mergedir,upperdir=temp/6e1bf8ee3b708647f06cac5e20e6998c1f55d1e89b311065c82727c7abbde134/contents,workdir=temp/workdir temp/mergedir
Traceback (most recent call last):
  File "./tern", line 94, in <module>
    main(args)
  File "./tern", line 53, in main
    report.execute_docker_image(args)
  File "/home/nisha/tern3.7/tern/report/report.py", line 324, in execute_docker_image
    analyze_docker_image(full_image)
  File "/home/nisha/tern3.7/tern/report/report.py", line 176, in analyze_docker_image
    image_obj.layers[index].tar_file)
  File "/home/nisha/tern3.7/tern/utils/rootfs.py", line 123, in mount_diff_layer
    root_command(union_mount, args, merge_dir_path)
  File "/home/nisha/tern3.7/tern/utils/rootfs.py", line 57, in root_command
    raise subprocess.CalledProcessError(1, cmd=full_cmd, output=error)
subprocess.CalledProcessError: Command '['sudo', 'mount', '-t', 'overlay', 'overlay', '-o', 'lowerdir=temp/mergedir,upperdir=temp/6e1bf8ee3b708647f06cac5e20e6998c1f55d1e89b311065c82727c7abbde134/contents,workdir=temp/workdir', 'temp/mergedir']' returned non-zero exit status 1.
```
Environment:
Fedora28 VM with updates

Log file attached
[tern.log](https://github.com/vmware/tern/files/2368880/tern.log)

**Comment by nishakm** [comment]
```
>>> try:
...     rootfs.mount_diff_layer("c96b61548d40e795197b8dd61fb531ab250ef51b592548a2b7baca71e5fe4c8c/layer.tar")
... except subprocess.CalledProcessError as e:
...     print(e.output)
...
b'mount: /home/nisha/tern3.7/tern/temp/mergedir: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.\n'
```
Where c96b61 is the 5th layer in the image and the 4th overlay mount.
